@extends('_layouts.clean')

@section('meta.title',          __('pages/index.meta_title'))
@section('meta.description',    __('pages/index.meta_description'))
@section('meta.keywords',       __('pages/index.meta_keywords'))


@section('PAGE_LEVEL_STYLES')
<!-- <link href="{{ asset('css/style.css') }}" rel="stylesheet">
<link href="{{ asset('css/style_new.css') }}" rel="stylesheet">

    <style type="text/css">
        .bannerSection {
            position: relative;
            display: none !important;
        }

        .headerSection nav.navbar.navbar-default {
            border-bottom: solid 2px #a0a0a000 !important;
        }
        .cp-terms-of-sup-content p {
            font-family: 'Calibri Light';
            font-size: 18px;
            color: #454545;
            margin: 10px 0;
        }
    </style> -->
@endsection

@section('PAGE_LEVEL_SCRIPTS')
<!-- <script type="text/javascript">
    $('.headerSection').show();
</script> -->
@endsection

@section('PAGE_START')
@endsection

@section('PAGE_END')
@endsection


@section('content')

    <div class="row innerPagesWrapper cp-terms-of-sup-content">
        <div class="container">
            <div class="row innerPageHead">
                <div class="col-sm-8">
                    <h3 class="title">Agreement as to Terms of Service for the use of the Elysium Capital EA portfolios Signal Platform</h3>
                </div>
                <div class="col-sm-4 innerLogo"><img src="{{ asset('images/InsiderLogoB.svg') }}" class="img-fluid"></div>
            </div>
            <p>By utilising this website, you agree to be bound by these terms and conditions. This is a legal agreement ("Agreement") between you and Elysium Capital Ltd., or any of its affiliated entities ("Elysium Capital") for use of the website, data, Elysium Capital electronic access platform, and products and services which you selected or initiated, which may include the Elysium Capital access platform and Elysium’s or third party EA signal providers c.q. proprietary trading desks, mentioned further underneath as signal providers ("Products and Services").</p>
            <h5>1. Scope - General Information</h5>
            <p class="font-weight-bold">1.1. Scope of agreement</p>
            <p>This is a legal agreement (hereinafter the "Agreement") between you and Elysium Capital Ltd. ("Elysium Capital") for use of the website, data, Elysium Capital electronic access platform, and products and services which you selected or initiated, which may include the Elysium Capital access platform and third party signal providers ("Products and Services").</p>
            <p class="font-weight-bold">1.2. Elysium Capital and the Elysium Capital EA portfolios signal provider Access Platform</p>
            <p>1.2.1. Elysium Capital is a technology provider that provides to a number of 3rd party FX 3rd party brokerages and to their respective clients the possibility to integrate in their business relationship the functionality of the Elysium Capital access platform (hereinafter the “Elysium Capital Platform” or the “Platform”).</p>
            <p>1.2.2. The Elysium Capital Platform is an automated access system, allowing a 3rd party brokerage’s client to reproduce in his/her trading account held with the 3rd party brokerage (the “Trading Account” or Managed Account), in an automated way and subject to the application of various parameters and limitations, clients can intervene at all times and are in full control of their EA portfolio trading signals generated by Elysium Capital or third parties (the “Signal Providers” or “Proprietary Trading desks”), as further set out in this agreement and explained on the Platform’s website.</p>
            <p>1.2.3. Any reference to your “Account” in the Platform and generally in relation to Elysium Capital, for the purposes of this Agreement, shall mean the personalised operation of the Platform concerning you, your relations with Elysium Capital and the transactions made by you through the use of the Platform’s functionality, as well as the capture and recording of such operation in the records and servers of Elysium Capital. Except for the purpose of receiving the applicable fees from the 3rd party brokerage and never from you, Elysium Capital shall not receive or keep money or other assets belonging to you and, therefore, the meaning of the term “Account”, as defined above, does not refer to the holding of any of your assets.</p>
            <p>Your assets are held in your 3rd party brokerage’s segregated accounts.</p>
            <p>1.2.4. Elysium Capital does not undertake, by this Agreement to conduct any of your transactions either as your counterparty or as your 3rd party brokerage and therefore assumes no liability in the event of non-performance (total or partial) or delayed execution of the signals generated through the Platform.</p>
            <p>1.2.5. Elysium Capital does not have formal involvement in the determination and provision of the products made available to you by any 3rd party brokerage, including the applicable leverage and spreads.</p>
            <h5>2. Rules and arrangements for the provision of the service</h5>
            <p class="font-weight-bold">2.1. Means of providing the service</p>
            <p>2.1.1. You have access to the Platform through the website www.elysiumcapital.io or any other website communicated for this purpose to you by Elysium Capital or your 3rd party brokerage.</p>
            <p>2.1.2. Given the nature of the Elysium Capital Platform, as provided through the use of electronic applications, you are required to make use of appropriate technical means (e.g. a computer, Internet connection etc.), as well as to have the necessary knowledge for the appropriate handling of such means. By entering into this agreement and accessing the Elysium Capital Platform, you acknowledge and confirm that you have the necessary equipment and sufficient expertise for its proper use.</p>
            <p>2.1.3. By using the Elysium Capital Signal Platform, you acknowledge that you understand and accept the risks associated with Internet-based trading services including, but not limited to, hardware, software or Internet connection related issues, and the potential inability of timely transmission of the relevant communication due to interruptions and/or errors. Since Elysium Capital does not control signal power, its reception or routing via Internet, the configuration of your hardware or software, or the reliability of your Internet connection, you agree that you are solely responsible for such failures, including communication failures, disruptions, distortions and delays in trading. Elysium Capital recommends that you should be cautious when you use an iPhone, Smart phone, Blackberry or other handheld mobile device for trading or receiving data from the Elysium Capital platform. Handheld mobile devices depend on wireless connectivity, are subject to the limitations of mobile data, WIFI and mobile communication networks restrictions, and may not provide you with the same functions as accessing the Elysium Capital platform from a web browser. Elysium Capital shall not be liable to any person for any losses, damages, costs or expenses (including, but not limited to, loss of profits, loss of use, direct, indirect, incidental or consequential damages) resulting from the use of a handheld mobile device.</p>
            <p>2.1.4. The use of the Elysium Capital Platform by you requires the combined use of your user name and password. The user name and password are created by Elysium Capital and sent to you after your registration in the Platform and remain private and strictly confidential. Elysium Capital may require for the activation of your access in the Platform a confirmatory email process or any other confirmation process ensuring that the identification data have been sent to/from you. The combined use of the user name and password by you establishes that the use of the Elysium Capital Platform and any activity in your Account (indicatively, choice of Signal Providers, Account settings, manual actions, information on performed transactions, etc.) is made by you. It will be your responsibility to protect the secrecy of the user-name and password, bearing exclusive liability for any damage suffered as a result of any leaks or use thereof by a third party in any way, with or without your authorisation. You may change the password at any time by following the relevant instructions listed on the website hosting the Platform, without any further disclosure of such change to Elysium Capital. For the purpose of preventing the use of the Elysium Capital Platform by a third party, it is recommended to change your password on a regular basis. Especially, in case of a leak of the user name or password, you shall immediately notify Elysium Capital and change the password.</p>
            <p class="font-weight-bold">2.2. No investment advice</p>
            <p>2.2.1. Elysium Capital shall not provide to you any kind of investment advice or other investment service. Elysium Capital offers solely the technical means that enable you to adopt trading strategies of signal providers of the Platform, based on the assumption that you have consciously chosen to conduct spot FX transactions with a 3rd party brokerage. Elysium Capital does not recommend/suggest to any user of the Platform any transactions in any financial instrument, nor does Elysium Capital represent that such transactions may be suitable or appropriate for you or any other user.</p>
            <p>2.2.2. The history and statistics of the 3rd party Signal Providers, the trading signals generated by the 3rdparty Signal Providers and the comments made by any Signal Provider on the Platform’s website do not constitute any kind of personal recommendation towards you or any other user to conduct or abstain from any transaction or to follow or unfollow any Signal Provider and should not be regarded as such.</p>
            <p class="font-weight-bold">2.3. Registration with the Platform</p>
            <p>Unless otherwise expressly agreed, your registration with the Platform is that of a normal user (i.e. not a Signal Provider) and this Agreement governs your relations with Elysium Capital under this specific and sole capacity.</p>
            <p class="font-weight-bold">2.4. Choice of Signal Providers</p>
            <p>The Platform provides you the opportunity to trade based on automated electronic trade signals. You may adjust the Platform’s settings so that it replicates in the Account the actions of one or more Signal Providers, portfolios, of your choice.</p>
            <p>The Signal Providers are third parties who use their signals (as displayed on the Platform) to carry out transactions for their own account, through 3rd party brokerages of their choice.</p>
            <p>The Platform may incorporate, from time to time, tools or features classifying the Signal Providers, portfolios, into specific categories, or attributing specific ratings or filtering a limited number of specific Signal Providers or combinations thereof. Such tools are based on the application of technical criteria to the Signal Providers’ past performance and statistics, in a way to bring to your attention Signal Providers or combinations thereof that may correspond to your trading preferences. In all such cases, you will be able to view the Signal Provider’s trading characteristics as well as to compare his trading history and performance with those of any other Signal Provider. By entering into this Agreement, you acknowledge your understanding that in no case, such classifications, ratings filtering or combinations of Signal Providers will be considered to constitute any kind of recommendation from Elysium Capital to follow any Signal Provider (or any combined strategies) with a view to achieve any specific future result.</p>
            <p>In the case of combinations of Signal Providers, the operation of the said combination may be subject to specific rules that Elysium Capital will communicate to you and that you will be requested to accept before proceeding to the choice of such combinations.</p>
            <p class="font-weight-bold">Application of settings to selected Systems</p>
            <p>The replication of a Signal Provider’s signals in your Account will always be subject to the restrictions applied by your 3rd party brokerage as to the offer of the products that you trade. In addition, you may choose specific settings and limits for the signals generated by each selected Signal Provider.</p>
            <p class="font-weight-bold">“Manual” actions</p>
            <p>The Platform enables you to introduce trading signals in your 3rd party brokerage Trading Account at your own initiative (manually)</p>
            <p class="font-weight-bold">2.7. Limitations of the services and of Elysium Capital’s responsibility</p>
            <p>2.7.1. Elysium Capital draws your attention to the following:</p>
            <p>- The 3rd party Signal Providers neither are related to Elysium Capital.</p>
            <p>- Elysium Capital does not intervene in the content of the signals produced by the Signal Providers.</p>

            <p>- The Signal Providers do not have access to and do not take into consideration any of the personal information or the position of the account of any of their respective followers.</p>

            <p>- Monitoring and evaluation of the Signal Providers by Elysium Capital takes place solely based on their past behavior and will in no case refer to their future behaviour or to the achievement of future performance.</p>

            <p>2.7.2. Although the Platform replicates exactly the signals of the relevant Signal Provider(s) (after applying any limitations set by you in your settings), delays in the execution of your transactions by your 3rd party brokerage are probable. It is also probable that divergences arise between the prices that any Signal Provider achieves, with respect to their own trades, and the prices that you achieve when following the signals of such Signal Provider, even if your trades are carried out at the same time as those of the Signal Provider. Such delays and divergences are normally attributable to the structure and function of the market, and particularly to (indicatively):</p>

            <p>The overall operation of the FX market, given that there is no single reference price for the participants in such a market.</p>

            <p>The special events occurring in the market, such as a steep price fluctuation (for example in the case of news announcement), a great volume of transactions waiting to be executed by your 3rd party brokerage or by your 3rd party brokerage’s liquidity provider.</p>

            <p>Volatility or illiquid in the Forex markets may also prevent orders from being executed at advantageous prices, or at all.</p>

            <p>Therefore, Elysium Capital does not guarantee:</p>

            <p>- An immediate and complete execution of the signals by your 3rd party brokerage.</p>

            <p>- The matching of the prices at which you carry out any specific trade with those at which the Signal Provider carries out the same trade.</p>

            <p>Generally, Elysium Capital shall not be liable to any person for any losses, damages, costs or expenses (including, but not limited to, loss of profits, loss of use, direct, indirect, incidental or consequential damages) occurring because trades cannot be executed due to market conditions, or from any errors of your 3rd party brokerage.</p>

            <p>2.7.4. By entering into this agreement, you acknowledge that you accept the risks inherent to the performance of transactions in the financial instruments supported by the Platform and provided to you by your 3rd party brokerage and that Elysium Capital bears no liability for these risks. In particular you acknowledge:</p>

            <p>i) That you are aware that transactions on financial instruments involve risks causing the reduction of the value of investments.</p>

            <p>ii) That foreign exchange, and other leveraged trading activities involve significant risk of loss. Such activity is not suitable for all investors and you should make sure you understand the risks involved, seeking independent advice if necessary.</p>

            <p>iii) That your trading results may vary depending on many factors. Because the risk factor is high in the foreign exchange, and other leveraged products, only genuine "risk" funds should be used in such trading. If you do not have the extra capital that you can afford to lose, you should not trade in leveraged products. No "safe" trading system has ever been devised, and no one can guarantee profits or freedom from loss.</p>

            <p>iv) That hypothetical performance results have many inherent limitations, some of which are described below. No representation is being made that any account will or is likely to achieve profits or losses similar to those shown. In fact, there are frequently sharp differences between hypothetical performance results and the actual results subsequently achieved by any particular trading program. One of the limitations of hypothetical performance results is that they are generally prepared with the benefit of hindsight. In addition, hypothetical trading does not involve financial risk, and no hypothetical trading record can completely account for the impact of financial risk in actual trading. For example, the ability to withstand losses or to adhere to a particular trading program in spite of trading losses are material points which can also adversely affect actual trading results. There are numerous other factors related to the markets in general or to the implementation of any specific trading program which cannot be fully accounted for in the preparation of hypothetical performance results and all of which can adversely affect actual trading results.</p>

            <p>v) That you are aware and accept the risks arising from the replication of investment strategies of third parties when using the Elysium Capital Platform and that past performance posted on the Platform is not indicative of future results.</p>

            <p>2.7.5. Elysium Capital shall not be responsible for any damage incurred by you (or a third party having any relevant right through you) due to force majeure (including the exercise of the right of strike, the malfunction of computers including the breakdown of computer systems or electronic communications), fraudulent usage of the data stored in its records and servers by third parties, failure of its electronic systems due to malfunctions of the communications’ network or malfunctioning of its software and hardware that is not attributable to the lack of maintenance or monitoring, as well as events related to the operation of third parties, such as interruption or suspension or limitation of the activities carried out by 3rd party brokerages to whom Elysium Capital introduces in the context of this agreement or third parties intervening in the course of your relationships and transactions with your 3rd party brokerage (exchanges, companies settling transactions, credit institutions etc.) for whatever reason.</p>

            <p>2.7.6. Elysium Capital is not responsible for the actions or omissions of your 3rd party brokerage or any other third party with respect to the transactions that you carry out with your 3rd party brokerage for whatever reason.</p>

            <p>2.7.7. Elysium Capital does not guarantee that the use of the Elysium Capital Platform will have a positive result or a specific performance for you. Any reference to the performance of transactions carried out by users of the Platform or Signal Providers is related exclusively to the past and by accepting these terms you acknowledge that you are aware of such fact. Any reference to the performances of any Signal Provider may not take into account the costs of transactions, such as 3rd party brokerage fees or any other fees applicable to your Elysium Capital Platform Account in the context of this Agreement.</p>

            <p>2.7.8. The trades conducted by Signal Provider on his own trading account may involve amounts greatly different from the amounts allocated by you to each transaction following the Signal Provider’s activity. This may itself cause a significantly different result compared to the Signal Provider’s profits or losses even if the remaining characteristics of your positions are the same as the ones of the specific Signal Provider. In addition, particular limitations may be applied to your trading account by your 3rd party brokerage, which may not necessarily apply to the Signal Provider at the same time. Such limitations may be due to specificity of the regulatory framework applicable to each 3rd party brokerage or to the 3rd party brokerage’s policies. The application of such limitations on your trading account may lead to further divergences between the results of the Signal Providers’ trades and your own trades, especially if the Signal Provider’s trading account is not subject to the same limitations.</p>

            <p class="font-weight-bold">2.8. Access to Market Data to Accounts</p>

            <p>The provision of access to certain categories of Market Data is subject to the acceptance by you of the terms. To the extent that the Market Data refers to a specific Market Data provider, such data will be terminated or amended or substituted in the event of termination of Elysium Capital’s relationship with the specific Market Data provider or in the event of substitution of the Market Data provider. In such a case Elysium Capital will apply its best endeavors in order to give you reasonable notice of the relevant event. In the case of substitution of the Market Data Provider, the provision of access to Market Data may be subject to the acceptance of additional terms by you.</p>

            <p>Access to Market Data is provided to you exclusively for internal/personal use. You may not sell, lease, furnish or otherwise permit or provide access to Market Data to any other Person or to any other office or place. You will not engage in the operation of any illegal business use or permit anyone else to use Market Data, or any part thereof, for any illegal purpose or violation of any Regulatory Requirements. You may not present Market Data rendered in any unfair, misleading, or discriminatory format. You shall take reasonable security precautions to prevent authorised persons from gaining access to Market Data.</p>

            <p class="font-weight-bold">2.9. Inability to access the Platform</p>

            <p>In case, for whatever reason, you are unable to access the Platform and its services, you must immediately notify Elysium Capital and contact your 3rd party brokerage directly to manage any open positions you have in your Trading Account. You may also request from your 3rd party brokerage to disconnect your account, while you are unable to access the Elysium Capital services, so as to avoid receiving new positions from Signal Providers in your Trading Account.</p>

            <h5>3. Communication</h5>

            <p class="font-weight-bold">3.1. Means of Communication</p>

            <p>The communication between you and Elysium Capital shall take place, depending on the case, either in writing or orally. More particularly:</p>

            <p>- The written communication takes place via documents exchange/shipping, via electronic mails being sent to the electronic addresses of the parties or via the Platform’s dedicated application for messages and communication.</p>

            <p>- Oral communication takes place in principle via telephone. Elysium Capital may tape record your telephone conversations with its employees, in order to prove the content of such conversations, as well as for the protection of your and Elysium Capital’s mutual interests. All such recorded telephone conversations may be stored in accordance with its Data Privacy Policy that is available on Elysium Capital’s website.</p>

            <p class="font-weight-bold">3.2. Confidentiality</p>

            <p>Elysium Capital will keep the information provided by you confidential under this agreement and take the necessary internal measures in order to ensure the confidentiality of such information. Confidentiality does not extend to any data or information</p>

            <p>a) That Elysium Capital has an obligation to disclose to the public or any competent authority,</p>

            <p>b) That have to be invoked by Elysium Capital before a Court or any competent authority for Elysium Capital’s defense with respect to a case pending against Elysium Capital relating to the relationships governed by this agreement,</p>

            <p>c) That has to be communicated to companies cooperating with Elysium Capital in order for the obligations undertaken by Elysium Capital under this agreement to be fulfilled.</p>

            <p class="font-weight-bold">3.3. Information regarding your trading activity</p>

            <p>Elysium Capital provides you with ongoing access to a personalised area of the Platform, in which you enter by using your individual codes, for the purpose of receiving at any time information on your trading activity at any period of time.</p>

            <p>Although Elysium Capital will apply its best efforts in order to provide you complete and accurate information in a timely manner, such information is not intended to substitute the information that your 3rd party brokerage is expected to provide to you with respect to the activity of your Trading Account. Consequently, Elysium Capital draws your attention to the fact that you must regularly check your Trading Account’s activity and content with your 3rd party brokerage, through the relevant applications, trading platforms or other communication means that are made available to you by your 3rd party brokerage.</p>

            <p>In case of various events that – in Elysium Capital’s reasonable opinion – may have an effect on your Account (such as a substantial change of trading behaviour by a Signal Provider that you may have selected), Elysium Capital may send you relevant notices through the Platform.</p>

            <p>Elysium Capital provides telephone helpline for the Platform. The relevant details can be found here: https://www.elysiumcapital.io/support</p>

            <p class="font-weight-bold">3.4. Probative force of book files and computer records</p>

            <p>Any copy or extract of the forms, data, books, records and files issued or kept by Elysium Capital, either in paper or in electronic form – in accordance with applicable legislation - or any extract of the Elysium Capital Account, which shall be exported by Elysium Capital and shall display the history of the Elysium Capital Account’s operation, shall constitute full proof for the activity of the Account. Similarly, extraction of logs regarding every aspect of the operation of your Account, including logs relating to your logging in the Platform and any use of the Platform by you, shall constitute full proof of the related facts.</p>

            <p class="font-weight-bold">3.5. Liability for transmission errors</p>

            <p>In cases of delay, interruptions or other errors that may occur during the transmission of electronic mail or fax, as well as in cases of incorrect translation or interpretation of technical terms, Elysium Capital shall only be liable for willful misconduct or gross negligence of its executives, agents or employees.</p>

            <h5>4. Fees</h5>

            <p class="font-weight-bold">4.2. Profit Sharing Account</p>

            <p>In addition to an optional Subscription Fee, you shall pay to Elysium Capital a percentage based Monthly Performance Fee per selected Signal Provider (portfolio). The Monthly Performance Fee shall be calculated on a monthly basis and shall be based upon your profit made from each selected Signal Provider that exceeds the Benchmark. For the purpose of this agreement, a “Benchmark” is defined as the net new high in profit of a Signal Provider at the end of a given monthly period, during the life of the Account. Profit shall be determined by taking into consideration the your equity at the end of each month, on all trading activity from each selected Signal Provider (which includes all open and closed positions) during the same month, comparing it to previous Benchmark(s).</p>

            <p>The Performance Fee will be applicable separately on each Signal Provider and not in the aggregate performance of the Account as a whole. Performance fees are automatically subtracted and your accounts are displayed in NAV (Net asset Value) by your 3rd party brokerage.</p>

            <h5>5. Authorisations</h5>

            <p>You hereby authorise Elysium Capital to access the Trading Account held by you with your 3rd party brokerage, via all appropriate technical means and - to the extent necessary - the relevant competent personnel and executives thereof, in order</p>

            <p>a) to connect the Platform to your Trading Account in a way to allow the introduction of the signals resulting from the operation of the Platform in your Trading Account;</p>

            <p>b) to obtain full information about your Trading Account connected to the Platform, in order to be able to provide comprehensive information to you via the Platform;</p>

            <p>c) to obtain information regarding your identification, for the purpose of providing the Elysium Capital Platform to you, receiving payments from you and complying with any applicable rules (including for the prevention of money laundering)</p>

            <p>d) to proceed to any other necessary consultation and collaboration with the 3rd party brokerage in order for the purpose of this agreement to be fulfilled.</p>

            <h5>6. Client’s Data</h5>

            <p class="font-weight-bold">6.1. Client’s identity</p>

            <p>For proof of your identity and that of any representatives designated by you, Elysium Capital may rely upon any document that, by law, is regarded as proof of identity of a person or legal entity. Elysium Capital shall not be responsible for the validity, legal integrity or authenticity of such documents. If you suffer loss by error, misunderstanding, deception or fraud as to the person giving instructions to Elysium Capital to carry out a specific action, Elysium Capital shall only be liable for willful misconduct or gross negligence of its executives, employees and agents.</p>

            <p class="font-weight-bold">6.2. Signature specimens</p>

            <p>Elysium Capital is entitled to receive and keep specimens of your and your representatives’ signatures, if necessary, for the fulfilment of the Service.</p>

            <p class="font-weight-bold">6.3. Change of data</p>

            <p>You shall notify Elysium Capital on your own initiative, without delay, of any change of name, contact information (especially e-mail address) and other data you have provided to Elysium Capital when entering into this agreement, as well as any change regarding the powers of representation granted to other persons (if applicable). You are not entitled to oppose Elysium Capital any change of the above data, if such change has not been notified to Elysium Capital in writing.</p>

            <p class="font-weight-bold">6.4. Personal Data</p>

            <p>Your personal data, as disclosed to Elysium Capital from time to time, will be stored, processed and disclosed to third parties for the purpose of providing the services and complying with Elysium Capital’s obligations, in accordance with Elysium Capital’s Data Privacy Policy, which is available through the link https://www.Elysium Capital.com/privacy-policy and the links provided therein).</p>

            <h5>7. Refund Policy</h5>

            <p>Elysium Capital shall not be responsible for refunding lost profits resulting from Platform Errors under any circumstances.</p>

            <p>Errors of Signal Providers or 3rd party brokerages shall not be considered Platform Errors, and Elysium Capital shall not be responsible for refunding losses or lost profits resulting from such errors under any circumstances.</p>

            <p>Except as expressly provided by this refund policy, neither Elysium Capital, nor our officers, principals, employees or agents shall be liable to any person for any losses, damages, costs or expenses (including, but not limited to, loss of profits, loss of use, direct, indirect, incidental or consequential damages) resulting from any errors in the Elysium Capital Platform.</p>

            <h5>8. Final provisions</h5>

            <p class="font-weight-bold">8.1. Representation regarding funds</p>

            <p>By accepting these terms and proceeding to the opening and operation of your Account, you represent and certify to Elysium Capital that</p>

            <p>a) all amounts of money that you have deposited and/or will deposit with your 3rd party brokerage belong to you, are from a legal source and do not derive from acts or activities falling within the prohibitions of the laws on the prevention and suppression of money laundering;</p>

            <p>b) generally you shall comply with the legal provisions and shall not engage in illegal or prohibited actions or practises;</p>

            <p>c) all information that you have provided or that you will provide to your 3rd party brokerage or to Elysium Capital regarding yourself and the origin of your assets are/will be true.</p>

            <p class="font-weight-bold">8.2. Restrictions to the use of Platform Information</p>

            <p>By viewing Elysium Capital’s website and trading on Platform, you fully understand and agree to respect the proprietary rights of Signal Providers and of Elysium Capital, and you represent that you do not desire to acquire from the Signal Providers any trade secrets or confidential information.</p>

            <p>You represent that you will be using signals solely for your own Elysium Capital Account and that you will not be reproducing such signals with any third party platforms or services outside of the Elysium Capital platform, without the written permission of Elysium Capital. Immediately upon notice from Elysium Capital that, in Elysium Capital’s opinion, any use of the Platform does not comply with this standard, you will cease such manner of use. Furthermore, you agree that Elysium Capital may at its sole discretion disable your access to the Platform at any time, in the case of system abuse or any infringement of any patent, copyright, trademark or other proprietary right or infringement upon a trade secret of any person or entity, or other reasons not described in this Agreement.</p>

            <p class="font-weight-bold">8.2. Duration – Termination</p>

            <p>This agreement is of indefinite duration. The agreement shall take effect after acceptance by the Client and upon the opening of the Account by Elysium Capital, and shall be terminated upon the closure of the Account. The Account may be closed either by a request from you, subject to Elysium Capital’s acceptance and provided that no Fees are outstanding, or in Elysium Capital’s initiative with a reasonable notice or – in the case of inactive accounts – with no notice.</p>

            <p class="font-weight-bold">8.3. Governing law – Jurisdiction</p>

            <p>8.2.1. All contractual relationships between Elysium Capital and the Client are governed by the laws of Hong Kong.</p>

            <p>8.2.2. The courts of Hong Kong will be competent for any dispute between you and Elysium Capital arising from this contractual relationship. Elysium Capital has the discretion to choose any other court having jurisdiction for the exercise of its claims against you.</p>

            <p class="font-weight-bold">8.3. Other terms</p>

            <p>8.3.1. The terms of this agreement shall only be amended by a written agreement between you and Elysium Capital (including by way of acceptance by electronic means), without prejudice to the provisions of the following paragraph.</p>

            <p>8.3.2. Elysium Capital shall have the right, at any time and under its sole and absolute discretion, to unilaterally change and/or amend the terms and conditions of this Agreement. You agree that any new format of this Agreement which shall be posted on Elysium Capital’s Website shall be considered as sufficient provision of notice for the changes and/or amendments made in such a new format and shall become effective as of the date of posting it as aforesaid.</p>

            <p>8.3.3. Any delay or omission of Elysium Capital to exercise any statutory or contractual right, in no way shall be deemed or construed as a waiver of the respective right.</p>

            <p>8.3.4. In case one or more the terms of this agreement is or becomes unenforceable, it shall not affect the validity of the remaining terms and the remaining provisions shall remain in force.</p>

            <p>8.3.5. You shall not assign or transfer in any way to third parties any of your rights and claims arising from your relations with Elysium Capital under this Agreement, unless otherwise agreed in writing.</p>


            <p>THIS CONCLUDES THE AGREEMENT</p>


        </div>
    </div>

@endsection
