<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMailTransactionTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('mail_transaction', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('mail_id');
            $table->unsignedInteger('user_id');
            $table->char('role', 50);
            $table->integer('starred');
            $table->integer('is_read');
            $table->integer('tag');
            $table->softDeletes();
            $table->nullableTimestamps();

            

            $table->foreign('mail_id', 'mail_transaction_ibfk_1')->references('id')->on('mail')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'mail_transaction_ibfk_10')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('mail_id', 'mail_transaction_ibfk_11')->references('id')->on('mail')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'mail_transaction_ibfk_12')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('mail_id', 'mail_transaction_ibfk_13')->references('id')->on('mail')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'mail_transaction_ibfk_14')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('mail_id', 'mail_transaction_ibfk_15')->references('id')->on('mail')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'mail_transaction_ibfk_16')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('mail_id', 'mail_transaction_ibfk_17')->references('id')->on('mail')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'mail_transaction_ibfk_18')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('mail_id', 'mail_transaction_ibfk_19')->references('id')->on('mail')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'mail_transaction_ibfk_2')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'mail_transaction_ibfk_20')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('mail_id', 'mail_transaction_ibfk_21')->references('id')->on('mail')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'mail_transaction_ibfk_22')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('mail_id', 'mail_transaction_ibfk_23')->references('id')->on('mail')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'mail_transaction_ibfk_24')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('mail_id', 'mail_transaction_ibfk_3')->references('id')->on('mail')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'mail_transaction_ibfk_4')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('mail_id', 'mail_transaction_ibfk_5')->references('id')->on('mail')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'mail_transaction_ibfk_6')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('mail_id', 'mail_transaction_ibfk_7')->references('id')->on('mail')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'mail_transaction_ibfk_8')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('mail_id', 'mail_transaction_ibfk_9')->references('id')->on('mail')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('mail_id', 'mail_transaction_mail_id_foreign')->references('id')->on('mail')->onDelete('CASCADE
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'mail_transaction_user_id_foreign')->references('id')->on('users')->onDelete('CASCADE
')->onUpdate('RESTRICT');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('mail_transaction');
    }
}
