<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateFundTransferTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('fund_transfer', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('transaction_id');
            $table->text('remark');
            $table->integer('from_wallet');
            $table->integer('to_wallet');

            $table->index('transaction_id', 'transaction_id');

            $table->foreign('transaction_id', 'fund_transfer_ibfk_1')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'fund_transfer_ibfk_10')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'fund_transfer_ibfk_11')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'fund_transfer_ibfk_2')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'fund_transfer_ibfk_3')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'fund_transfer_ibfk_4')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'fund_transfer_ibfk_5')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'fund_transfer_ibfk_6')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'fund_transfer_ibfk_7')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'fund_transfer_ibfk_8')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'fund_transfer_ibfk_9')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('fund_transfer');
    }
}
