<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateConfigFieldsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('config_fields', function (Blueprint $table) {
            $table->increments('id');
            $table->char('field_type', 30);
            $table->char('link', 200);
            $table->char('field_name', 30);
            $table->text('placeholder');
            $table->text('label');
            $table->char('field_group', 30);
            $table->text('field_choices');
            $table->text('field_validation');
            $table->integer('sort_order');
            $table->text('conditional_rules');
            $table->nullableTimestamps();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('config_fields');
    }
}
