<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('customer_id', 11);
            $table->string('username', 191);
            $table->string('email', 191);
            $table->integer('status');
            $table->string('password', 191);
            $table->string('phone', 191);
            $table->softDeletes();
            $table->rememberToken();
            $table->nullableTimestamps();

            $table->unique('username', 'users_username_unique');
            $table->unique('email', 'users_email_unique');
            $table->unique('customer_id', 'customer_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
