<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateInvestmentRoiTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('investment_roi', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('client_id');
            $table->double('invested_amount')->nullable();
            $table->double('profit')->default(0);
            $table->dateTime('created_at');
            $table->dateTime('updated_at');

            $table->foreign('client_id')->references('id')->on('investment_clients')->onDelete('CASCADE')->onUpdate('CASCADE');

        });



    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('investment_roi');
    }
}
