<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePackagesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('packages', function (Blueprint $table) {
            $table->increments('id');
            $table->string('slug', 30);
            $table->string('name', 50);
            $table->double('price')->default(0);
            $table->double('upgrade_price');
            $table->double('pv')->default(0);
            $table->double('upgrade_pv');
            $table->text('description');
            $table->tinyInteger('status')->default(1);
            $table->string('image', 191);
            $table->tinyInteger('in_registration');
            $table->tinyInteger('in_upgrade');
            $table->integer('validity_in_month');
            $table->nullableTimestamps();
            $table->softDeletes();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('packages');
    }
}
