<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateBinaryPointsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('binary_points', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('user_id');
            $table->double('point');
            $table->tinyInteger('position');
            $table->tinyInteger('is_credit');
            $table->double('pair');
            $table->integer('pair_id');
            $table->double('possible_pair');
            $table->integer('from_user')->nullable();
            $table->char('context', 20)->nullable();
            $table->softDeletes();
            $table->nullableTimestamps();

            $table->index('user_id', 'user_id');

            $table->foreign('user_id', 'binary_points_ibfk_1')->references('id')->on('users')->onDelete('RESTRICT')->onUpdate('RESTRICT');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('binary_points');
    }
}
