<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateOrdersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('orders', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('user_id');
            $table->unsignedInteger('transaction_id');
            $table->integer('status');
            $table->char('ip', 50);
            $table->char('order_type', 50);
            $table->char('user_agent', 50);
            $table->char('payment_gateway', 200);
            $table->double('total');
            $table->double('subtotal');
            $table->double('discount');
            $table->tinyInteger('isPackage')->default(0);
            $table->nullableTimestamps();



            $table->foreign('user_id', 'orders_user_id_foreign')->references('id')->on('users')->onDelete('CASCADE')->onUpdate('RESTRICT');

        });



    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('orders');
    }
}
