<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateEwalletTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ewallet', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('user_id');
            $table->char('transaction_password', 200);
            $table->char('card_number', 50)->nullable();
            $table->char('cvv', 50)->nullable();
            $table->char('ip', 50)->nullable();
            $table->tinyInteger('ip_status')->nullable();
            $table->tinyInteger('status')->nullable();
            $table->nullableTimestamps();

            

            $table->foreign('user_id', 'ewallet_user_id_foreign')->references('id')->on('users')->onDelete('CASCADE
')->onUpdate('RESTRICT');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ewallet');
    }
}
