<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateActivityHistoryTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('activity_history', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('activity_id');
            $table->integer('user_id');
            $table->text('data');
            $table->char('ip', 25);
            $table->nullableTimestamps();

            $table->index('activity_id', 'activity_id');

            $table->foreign('activity_id', 'activity_history_ibfk_1')->references('id')->on('activities')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('activity_id', 'activity_history_ibfk_2')->references('id')->on('activities')->onDelete('RESTRICT
')->onUpdate('RESTRICT');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('activity_history');
    }
}
