<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateEasyRoutesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('easy_routes', function (Blueprint $table) {
            $table->increments('id');
            $table->char('route_name', 50)->nullable();
            $table->char('route_uri', 100);
            $table->char('route_controller', 100)->nullable();
            $table->char('title', 50)->nullable();
            $table->text('description')->nullable();
            $table->char('route_params', 50)->nullable();
            $table->softDeletes();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('easy_routes');
    }
}
