<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateXoomUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('xoom_users', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('user_id');
            $table->unsignedBigInteger('xoom_user_id')->nullable();
            $table->text('access_token')->nullable();
            $table->nullableTimestamps();
            $table->softDeletes();

            $table->unique('user_id', 'xoom_users_user_id_unique');

            $table->foreign('user_id', 'xoom_users_user_id_foreign')->references('id')->on('users')->onDelete('CASCADE
')->onUpdate('CASCADE');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('xoom_users');
    }
}
