<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePayoutRequestsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('payout_requests', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('user_id');
            $table->double('request_amount');
            $table->double('release_amount');
            $table->integer('wallet');
            $table->integer('gateway');
            $table->text('remark');
            $table->integer('status');
            $table->unsignedInteger('transaction_id');
            $table->integer('account');
            $table->softDeletes();
            $table->nullableTimestamps();

            $table->index('user_id', 'user_id');
            $table->index('transaction_id', 'transaction_id');

            $table->foreign('user_id', 'payout_requests_ibfk_1')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'payout_requests_ibfk_10')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'payout_requests_ibfk_11')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'payout_requests_ibfk_12')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'payout_requests_ibfk_13')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'payout_requests_ibfk_14')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'payout_requests_ibfk_15')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'payout_requests_ibfk_16')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'payout_requests_ibfk_2')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'payout_requests_ibfk_3')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'payout_requests_ibfk_4')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'payout_requests_ibfk_5')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'payout_requests_ibfk_6')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'payout_requests_ibfk_7')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'payout_requests_ibfk_8')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'payout_requests_ibfk_9')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('payout_requests');
    }
}
