<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTransactionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('transactions', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('payer');
            $table->unsignedInteger('payee');
            $table->string('context', 191);
            $table->integer('gateway');
            $table->double('amount');
            $table->double('actual_amount');
            $table->string('ip', 191);
            $table->integer('status')->default(1);
            $table->softDeletes();
            $table->nullableTimestamps();



            $table->foreign('payer', 'transactions_ibfk_1')->references('id')->on('users')->onDelete('RESTRICT')->onUpdate('RESTRICT');

        });



    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('transactions');
    }
}
