<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserSubTypesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_sub_types', function (Blueprint $table) {
            $table->increments('id');
            $table->char('title', 255);
            $table->unsignedInteger('user_type_id');
            $table->longText('privilege')->nullable();
            $table->nullableTimestamps();
            $table->softDeletes();

            

            $table->foreign('user_type_id', 'user_sub_types_user_type_id_foreign')->references('id')->on('user_types')->onDelete('CASCADE
')->onUpdate('RESTRICT');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_sub_types');
    }
}
