<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserRepoTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_repo', function (Blueprint $table) {
            $table->unsignedInteger('user_id');
            $table->integer('sponsor_id');
            $table->integer('parent_id')->default(0);
            $table->integer('LHS')->default(0);
            $table->integer('RHS')->default(0);
            $table->integer('SLHS')->default(0);
            $table->integer('SRHS')->default(0);
            $table->integer('position')->default(0);
            $table->integer('user_level')->default(0);
            $table->integer('sp_user_level')->default(0);
            $table->integer('status_id')->default(1);
            $table->integer('package_id');
            $table->softDeletes();
            $table->nullableTimestamps();
            $table->date('expiry_date')->nullable();
            $table->string('default_binary_position', 191)->default(3);

            $table->unique('user_id', 'user_repo_user_id_unique');

            $table->foreign('user_id', 'aaaa')->references('id')->on('users')->onDelete('CASCADE
')->onUpdate('CASCADE');
            $table->foreign('user_id', 'user_repo_ibfk_1')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'user_repo_ibfk_2')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('user_id', 'user_repo_ibfk_3')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');

        });



    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_repo');
    }
}
