<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateConfigFieldGroupsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('config_field_groups', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('parent')->nullable();
            $table->text('title');
            $table->char('slug', 50);
            $table->text('description');
            $table->char('iconFont', 50)->nullable();
            $table->char('image', 50)->nullable();
            $table->text('style')->nullable();
            $table->integer('tag_id')->nullable();
            $table->integer('sort_order')->default(0);
            $table->tinyInteger('core');
            $table->tinyInteger('editable');
            $table->nullableTimestamps();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('config_field_groups');
    }
}
