<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTransactionDetailsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('transaction_details', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('transaction_id');
            $table->char('remarks', 250)->nullable();
            $table->integer('from_module');
            $table->integer('to_module');
            $table->unsignedInteger('operation_id');

            $table->index('transaction_id', 'transaction_id');
            $table->index('operation_id', 'operation_id');

            $table->foreign('transaction_id', 'transaction_details_ibfk_1')->references('id')->on('transactions')->onDelete('RESTRICT')->onUpdate('RESTRICT');
            $table->foreign('operation_id', 'transaction_details_ibfk_10')->references('id')->on('transaction_operations')->onDelete('RESTRICT')->onUpdate('RESTRICT');

        });



    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('transaction_details');
    }
}
