<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTransactionChargesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('transaction_charges', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('transaction_id');
            $table->unsignedInteger('module_id');
            $table->double('amount');
            $table->tinyInteger('is_credit');

            $table->index('transaction_id', 'transaction_id');
            $table->index('module_id', 'module_id');

            $table->foreign('transaction_id', 'transaction_charges_ibfk_1')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('module_id', 'transaction_charges_ibfk_10')->references('id')->on('modules')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'transaction_charges_ibfk_11')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('module_id', 'transaction_charges_ibfk_12')->references('id')->on('modules')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'transaction_charges_ibfk_13')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('module_id', 'transaction_charges_ibfk_14')->references('id')->on('modules')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('module_id', 'transaction_charges_ibfk_2')->references('id')->on('modules')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'transaction_charges_ibfk_3')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('module_id', 'transaction_charges_ibfk_4')->references('id')->on('modules')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'transaction_charges_ibfk_5')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('module_id', 'transaction_charges_ibfk_6')->references('id')->on('modules')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'transaction_charges_ibfk_7')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('module_id', 'transaction_charges_ibfk_8')->references('id')->on('modules')->onDelete('RESTRICT
')->onUpdate('RESTRICT');
            $table->foreign('transaction_id', 'transaction_charges_ibfk_9')->references('id')->on('transactions')->onDelete('RESTRICT
')->onUpdate('RESTRICT');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('transaction_charges');
    }
}
