<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateOrderProductsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('order_products', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('order_id');
            $table->unsignedInteger('product_id');
            $table->integer('quantity');
            $table->char('order_type', 50);
            $table->double('price');
            $table->double('pv');
            $table->double('subtotal');
            $table->double('total');
            $table->double('discount');
            $table->tinyInteger('is_package');
            $table->nullableTimestamps();

            $table->foreign('order_id', 'order_products_ibfk_1')->references('id')->on('orders')->onDelete('RESTRICT')->onUpdate('RESTRICT');
            $table->foreign('product_id', 'order_products_ibfk_11')->references('id')->on('packages')->onDelete('RESTRICT')->onUpdate('RESTRICT');

        });



    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('order_products');
    }
}
