<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCronHistoryTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('cron_history', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('cron_id');
            $table->longText('response');
            $table->nullableTimestamps();

            $table->index('cron_id', 'cron_id');

            $table->foreign('cron_id')->references('id')->on('cron_jobs')->onDelete('RESTRICT')->onUpdate('RESTRICT');

        });



    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('cron_history');
    }
}
