<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateBookmarkTypesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('bookmark_types', function (Blueprint $table) {
            $table->increments('id');
            $table->text('label');
            $table->char('slug', 50);
            $table->text('description')->nullable();
            $table->char('view_component', 200)->nullable();
            $table->char('icon_font', 50)->nullable();
            $table->text('icon_image')->nullable();
            $table->integer('sort_order')->nullable();
            $table->nullableTimestamps();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('bookmark_types');
    }
}
