<?php

use App\Http\Validators\Panel\User\AccountInformationValidator;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCapitalUserScmCashCallbacksTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('capital_user_scm_cash_callbacks', function (Blueprint $table) {
            $table->bigIncrements('id')->unsigned();
            $table->bigInteger('capital_user_id')->unsigned();
            $table->integer('message_id');
            $table->integer('ticket_id');
            $table->string('group', 128);
            $table->enum('currency', AccountInformationValidator::$currency);
            $table->decimal('amount', 8, 6);
            $table->decimal('deposit', 8, 6)->nullable();
            $table->decimal('withdrawal', 8, 6)->nullable();
            $table->string('comment', 128)->nullable();
            $table->timestamp('time');
            $table->timestamps();

            $table->foreign('capital_user_id')->references('id')->on('capital_users')->onDelete('cascade');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('capital_user_scm_cash_callbacks');
    }
}
