<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateHoldingTankTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('holding_tank', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('user_id');
            $table->unsignedInteger('sponsor_id')->nullable();
            $table->tinyInteger('status')->nullable();
            $table->char('default_position', 191);
            $table->nullableTimestamps();
            $table->softDeletes();

            $table->index('user_id', 'user_id');
            $table->index('sponsor_id', 'sponsor_id');

            $table->foreign('sponsor_id', 'holding_tank_ibfk_2')->references('id')->on('users')->onDelete('CASCADE
')->onUpdate('CASCADE');
            $table->foreign('user_id', 'holding_tank_ibfk_1')->references('id')->on('users')->onDelete('CASCADE
')->onUpdate('CASCADE');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('holding_tank');
    }
}
