<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateB2bTransactionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('b2b_transactions', function (Blueprint $table) {
            $table->increments('id');
            $table->char('address', 200)->nullable();
            $table->char('local_txn_id', 200)->nullable();
            $table->char('context', 200)->nullable();
            $table->char('callback', 200)->nullable();
            $table->integer('sort_order')->nullable();
            $table->double('amount')->nullable();
            $table->longText('data')->nullable();
            $table->tinyInteger('status')->nullable()->default(0);
            $table->nullableTimestamps();

        });



    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('b2b_transactions');
    }
}
