<?php

use App\Http\Validators\Panel\User\AccountInformationValidator;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCapitalUserScmCashBalanceTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('capital_user_scm_cash_balance', function (Blueprint $table) {
            $table->bigIncrements('id')->unsigned();
            $table->bigInteger('capital_user_id')->unsigned();
            $table->string('login', 64)->nullable();
            $table->string('name', 128)->nullable();
            $table->enum('currency', AccountInformationValidator::$currency);
            $table->string('group', 128);
            $table->decimal('balance', 8, 6);
            $table->decimal('deposit', 8, 6)->nullable();
            $table->decimal('credit', 8, 6)->nullable();
            $table->decimal('profit', 8, 6)->nullable();
            $table->decimal('profitclosed', 8, 6)->nullable();
            $table->decimal('equity', 8, 6);
            $table->decimal('margin', 8, 6)->nullable();
            $table->decimal('marginfree', 8, 6)->nullable();
            $table->date('yearmonth');

            $table->timestamps();

            $table->unique([
                'capital_user_id',
                'yearmonth'
            ]);

            $table->foreign('capital_user_id')->references('id')->on('capital_users')->onDelete('cascade');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('capital_user_scm_cash_balance');
    }
}
